spring:
  redis:
    # Redis索引默认（0 - 15，默认为0）
    database: 0
    # 默认连接地址URL
    host: 127.0.0.1
    # Redis密码，如果没有不用配置
    password: HAPPY
    # Redis端口号
    port: 6379
    # Redis连接的超时时间
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大连接数（负数表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
